# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      ZUSQII  -  K I T T Y  C O L O R S  (matugen generated)      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

background            #111418
foreground            #e1e2e8

cursor                #a1cafd
cursor_text_color     #003259

selection_background  #3c4858
selection_foreground  #d7e3f8

url_color             #d7bee4

# Black
color0   #1d2024
color8   #272a2f

# Red
color1   #ffb4ab
color9   #93000a

# Green
color2   #d7bee4
color10  #533f5f

# Yellow
color3   #bbc7db
color11  #3c4858

# Blue
color4   #a1cafd
color12  #1b4975

# Magenta
color5   #f3daff
color13  #f3daff

# Cyan
color6   #37618e
color14  #d2e4ff

# White
color7   #c3c6cf
color15  #e1e2e8

# Tabs
active_tab_background   #1b4975
active_tab_foreground   #d2e4ff
inactive_tab_background #1d2024
inactive_tab_foreground #c3c6cf
tab_bar_background      #111418
