foreground            #e3e1e9
background            #121318
cursor                #e3e1e9

selection_foreground  #dfe1f9
selection_background  #424659

color0  #34343a
color8  #90909a

color1  #ffb4ab
color9  #ffb4ab

color2  #b8c3ff
color10 #b8c3ff

color3  #e4bad9
color11 #e4bad9

color4  #c3c5dd
color12 #c3c5dd

color5  #b8c3ff
color13 #b8c3ff

color6  #c3c5dd
color14 #c3c5dd

color7  #e3e1e9
color15 #c6c5d0
